MODE_BACKTEST = "BACKTEST"
MODE_PAPER = "PAPER"
MODE_REAL = "REAL"
MODE_SHADOW = "SHADOW"

SUPPORTED_MODES = {MODE_BACKTEST, MODE_PAPER, MODE_REAL, MODE_SHADOW}

SIDE_CE = "CE"
SIDE_PE = "PE"
SIDE_WAIT = "WAIT"

SUPPORTED_UNDERLYINGS = {"NIFTY", "SENSEX", "BANKNIFTY", "BANKEX"}
DEFAULT_ENABLED_UNDERLYINGS = {"NIFTY", "SENSEX"}

ORDER_TYPE_LIMIT = "LIMIT"
ORDER_TYPE_SL = "SL"

REAL_EXECUTION_DISABLED_REASON = (
    "Real order execution is disabled in this Options Auto foundation phase. "
    "Use dry-run readiness, shadow, backtest, or paper simulation only."
)

