from __future__ import annotations

from copy import deepcopy
from typing import Any

from options_auto.constants import MODE_PAPER


DEFAULT_OPTIONS_AUTO_SETTINGS: dict[str, Any] = {
    "mode": MODE_PAPER,
    "underlying": "NIFTY",
    "enabled_underlyings": ["NIFTY", "SENSEX"],
    "chart_interval": "3minute",
    "strategy_profile": "BALANCED",
    "entry_dependency_mode": "OHLCV_VOLUME_PROFILE",
    "aggressive_uses_simple_ohlcv_entry": True,
    "simple_ohlcv_score_threshold": 50.0,
    "simple_ohlcv_side_score_threshold": 35.0,
    "simple_ohlcv_min_relative_volume": 0.0,
    "paper_starting_balance": 20000.0,
    "buy_score_threshold": 50.0,
    "approval_timeout_seconds": 30,
    "ask_permission_before_entry": True,
    "auto_entry_enabled": False,
    "adaptive_live_enabled": True,
    "fast_final_validation_enabled": True,
    "ready_plan_cache_enabled": True,
    "require_fii_dii_upload": False,
    "allow_demo_data": False,
    "real_orders_enabled": False,
    "confirm_real_mode": False,
    "static_ip_confirmed": False,
    "allow_real_emergency_orders": False,
    "max_capital_per_trade_pct": 20.0,
    "max_risk_per_trade_pct": 2.5,
    "number_of_lots": 1,
    "max_lots_per_trade": 2,
    "max_trades_per_day": 3,
    "max_open_trades": 1,
    "max_daily_loss": 1000.0,
    "max_daily_profit_lock": 2500.0,
    "max_consecutive_losses": 2,
    "cooldown_after_trade_seconds": 300,
    "cooldown_after_loss_seconds": 600,
    "cooldown_after_rejection_seconds": 180,
    "cooldown_after_api_error_seconds": 300,
    "avoid_first_minutes": 15,
    "no_new_trade_after": "15:00",
    "square_off_time": "15:15",
    "buy_order_type": "LIMIT",
    "target_order_type": "LIMIT",
    "stoploss_order_type": "SL",
    "limit_order_timeout_seconds": 30,
    "modify_limit_allowed": True,
    "max_buy_limit_modifications": 2,
    "max_signal_age_seconds": 20,
    "max_chase_points": 3.0,
    "max_chase_atr_fraction": 0.35,
    "slippage_buffer_points": 0.10,
    "slippage_buffer_pct": 0.0,
    "max_allowed_slippage_points": 5.0,
    "max_spread_pct": 0.60,
    "min_depth_qty": 1,
    "min_volume": 0,
    "min_oi": 0,
    "quote_stale_seconds": 3.0,
    "market_cue_alignment_required": False,
    "news_sentiment_weight": 3.0,
    "trend_strength_threshold": 55.0,
    "atr_target_multiplier": 1.5,
    "atr_stoploss_multiplier": 1.0,
    "min_stoploss_pct": 3.0,
    "minimum_stoploss_points": 2.0,
    "minimum_profit_buffer_points": 1.0,
    "estimated_total_charges": 40.0,
    "estimated_charges_per_lot": 40.0,
    "capital_buffer_pct": 5.0,
    "expected_holding_minutes": 15,
    "adaptive_scan_seconds_aggressive": 1,
    "adaptive_scan_seconds_balanced": 2,
    "adaptive_scan_seconds_conservative": 3,
    "max_plan_age_seconds_aggressive": 3,
    "max_plan_age_seconds_balanced": 5,
    "max_plan_age_seconds_conservative": 8,
    "pending_entry_check_seconds": 1,
    "active_trade_check_seconds": 1,
    "allow_target_extension": True,
    "expiry_scalp_extension_enabled": False,
    "target_extension_atr_fraction": 0.8,
    "target_extension_target_fraction": 0.5,
    "target_extension_profit_protection_pct": 40.0,
    "premium_stagnation_candles": 3,
    "minimum_sl_improvement_ticks": 2,
    "early_exit_min_conditions": 3,
    "aggressive_mode_min_score": 75.0,
    "low_aggression_score_boost": 10.0,
    "reduce_quantity_on_low_aggression": True,
    "low_aggression_quantity_pct": 50,
    "pending_entry_dynamic_cancel_enabled": True,
    "pending_entry_dynamic_modify_enabled": True,
    "final_validation_latency_warning_ms": 200.0,
    "action_latency_warning_ms": 500.0,
    "atm_scan_strike_span": 4,
    "major_strike_selection_enabled": True,
    "major_strike_step": 100,
    "use_major_strikes_only": True,
    "contract_reselection_minutes": 60,
    "max_hop_strikes": 5,
    "lock_contracts_until_trade_or_timeout": True,
    "reselect_after_exit_cooldown": True,
    "strict_liquidity_filter": False,
    "auto_expiry_switch": False,
    "expiry_scalping_mode": False,
    "same_day_expiry_cutoff_time": "11:30",
    "premium_expansion_required": False,
    "expiry_scalp_enabled": False,
    "allow_expiry_far_otm": False,
    "late_scalp_enabled": False,
    "backtest_entry_mode": "NEXT_CANDLE_OPEN_PLUS_SLIPPAGE",
    "backtest_conservative_limit_fill": True,
    "backtest_entry_validity_candles": 1,
    "buy_limit_offset_multiplier": 0.25,
    "minimum_limit_offset_points": 0.5,
    "maximum_limit_offset_points": 2.0,
    "trailing_stop_enabled": True,
    "partial_exit_enabled": False,
    "break_even_sl_enabled": True,
    "time_exit_enabled": True,
    "reversal_exit_enabled": True,
    "volatility_exit_enabled": True,
    "max_holding_minutes": 45,
    "sl_modify_throttle_seconds": 10,
    "theta_exit_risk_score": 80.0,
    "iv_crush_exit_pct": 25.0,
    "max_latency_warning_ms": 1500.0,
    "telegram_command_cooldown_seconds": 2,
    "telegram_duplicate_window_seconds": 10,
    "require_telegram_position_preview": True,
    "expiry_preference": "AUTO",
    "allow_deep_otm": False,
    "expiry_day_max_lots": 1,
    "dry_run_real_only": True,
    "real_auto_entry_enabled": False,
    "real_entry_poll_seconds": 1,
    "real_entry_timeout_seconds": 30,
    "partial_fill_protect_immediately": True,
    "cancel_unfilled_entry_after_timeout": True,
    "real_protection_retry_count": 2,
    "real_protection_retry_delay_seconds": 1,
    "real_order_update_source": "POLLING_AND_RECONCILIATION",
    "allow_real_emergency_flatten": False,
    "emergency_flatten_order_type": "AGGRESSIVE_LIMIT",
    "emergency_flatten_market_allowed": False,
    "emergency_flatten_max_slippage_points": 2.0,
    "emergency_flatten_verify_timeout_seconds": 10,
    "emergency_flatten_poll_interval_seconds": 1,
    "options_live_feed_enabled": True,
    "options_websocket_primary_enabled": True,
    "websocket_order_updates_enabled": True,
    "event_driven_decisions_enabled": True,
    "event_driven_min_scan_interval_ms": 500,
    "runtime_state_persistence_enabled": True,
    "options_auto_runtime_persist_min_interval_seconds": 2.0,
    "options_auto_runtime_persist_async_enabled": False,
    "prewarm_reference_data_on_start": True,
    "incremental_feature_cache_enabled": True,
    "quote_polling_fallback_enabled": True,
    "max_tick_age_seconds": 3,
    "max_quote_age_seconds": 3,
    "websocket_reconnect_max_attempts": 5,
    "websocket_reconnect_backoff_seconds": 2,
    "pause_entries_on_feed_stale": True,
    "backtest_reselect_contracts_using_index_candle_close": True,
    "max_full_quote_batch_size": 500,
    "quote_snapshot_min_interval_seconds": 1,
    "quote_failure_backoff_seconds": 5,
    "quote_error_pause_new_entries": True,
    "real_broker_reconcile_poll_seconds": 10,
}


def default_settings() -> dict[str, Any]:
    return deepcopy(DEFAULT_OPTIONS_AUTO_SETTINGS)


def _bool(value: Any, default: bool) -> bool:
    if value in ("", None):
        return default
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in {"1", "true", "yes", "y", "on", "enabled"}


def _float(value: Any, default: float) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return float(default)


def _int(value: Any, default: int) -> int:
    try:
        return int(float(value))
    except (TypeError, ValueError):
        return int(default)


def normalize_settings(payload: dict[str, Any] | None) -> dict[str, Any]:
    settings = default_settings()
    payload = dict(payload or {})
    settings.update({key: value for key, value in payload.items() if value not in (None, "")})

    for key in (
        "ask_permission_before_entry",
        "auto_entry_enabled",
        "adaptive_live_enabled",
        "fast_final_validation_enabled",
        "ready_plan_cache_enabled",
        "require_fii_dii_upload",
        "allow_demo_data",
        "real_orders_enabled",
        "confirm_real_mode",
        "static_ip_confirmed",
        "allow_real_emergency_orders",
        "modify_limit_allowed",
        "market_cue_alignment_required",
        "premium_expansion_required",
        "allow_target_extension",
        "expiry_scalp_extension_enabled",
        "reduce_quantity_on_low_aggression",
        "pending_entry_dynamic_cancel_enabled",
        "pending_entry_dynamic_modify_enabled",
        "expiry_scalp_enabled",
        "allow_expiry_far_otm",
        "late_scalp_enabled",
        "backtest_conservative_limit_fill",
        "trailing_stop_enabled",
        "partial_exit_enabled",
        "break_even_sl_enabled",
        "time_exit_enabled",
        "reversal_exit_enabled",
        "volatility_exit_enabled",
        "allow_deep_otm",
        "dry_run_real_only",
        "real_auto_entry_enabled",
        "partial_fill_protect_immediately",
        "cancel_unfilled_entry_after_timeout",
        "options_live_feed_enabled",
        "options_websocket_primary_enabled",
        "websocket_order_updates_enabled",
        "event_driven_decisions_enabled",
        "runtime_state_persistence_enabled",
        "options_auto_runtime_persist_async_enabled",
        "prewarm_reference_data_on_start",
        "incremental_feature_cache_enabled",
        "quote_polling_fallback_enabled",
        "pause_entries_on_feed_stale",
        "backtest_reselect_contracts_using_index_candle_close",
        "quote_error_pause_new_entries",
        "require_telegram_position_preview",
        "major_strike_selection_enabled",
        "use_major_strikes_only",
        "lock_contracts_until_trade_or_timeout",
        "reselect_after_exit_cooldown",
        "strict_liquidity_filter",
        "auto_expiry_switch",
        "expiry_scalping_mode",
        "aggressive_uses_simple_ohlcv_entry",
    ):
        settings[key] = _bool(settings.get(key), bool(DEFAULT_OPTIONS_AUTO_SETTINGS[key]))

    for key in (
        "paper_starting_balance",
        "buy_score_threshold",
        "simple_ohlcv_score_threshold",
        "simple_ohlcv_side_score_threshold",
        "simple_ohlcv_min_relative_volume",
        "max_capital_per_trade_pct",
        "max_risk_per_trade_pct",
        "max_daily_loss",
        "max_daily_profit_lock",
        "slippage_buffer_points",
        "slippage_buffer_pct",
        "max_allowed_slippage_points",
        "max_chase_points",
        "max_chase_atr_fraction",
        "max_spread_pct",
        "quote_stale_seconds",
        "news_sentiment_weight",
        "trend_strength_threshold",
        "atr_target_multiplier",
        "atr_stoploss_multiplier",
        "min_stoploss_pct",
        "minimum_stoploss_points",
        "minimum_profit_buffer_points",
        "estimated_total_charges",
        "estimated_charges_per_lot",
        "capital_buffer_pct",
        "target_extension_atr_fraction",
        "target_extension_target_fraction",
        "target_extension_profit_protection_pct",
        "aggressive_mode_min_score",
        "low_aggression_score_boost",
        "final_validation_latency_warning_ms",
        "action_latency_warning_ms",
        "theta_exit_risk_score",
        "iv_crush_exit_pct",
        "max_latency_warning_ms",
        "quote_snapshot_min_interval_seconds",
        "quote_failure_backoff_seconds",
        "websocket_reconnect_backoff_seconds",
        "options_auto_runtime_persist_min_interval_seconds",
    ):
        settings[key] = _float(settings.get(key), float(DEFAULT_OPTIONS_AUTO_SETTINGS[key]))

    for key in (
        "approval_timeout_seconds",
        "number_of_lots",
        "max_lots_per_trade",
        "max_trades_per_day",
        "max_open_trades",
        "max_consecutive_losses",
        "cooldown_after_trade_seconds",
        "cooldown_after_loss_seconds",
        "cooldown_after_rejection_seconds",
        "cooldown_after_api_error_seconds",
        "avoid_first_minutes",
        "limit_order_timeout_seconds",
        "max_buy_limit_modifications",
        "max_signal_age_seconds",
        "min_depth_qty",
        "min_volume",
        "min_oi",
        "max_holding_minutes",
        "expected_holding_minutes",
        "adaptive_scan_seconds_aggressive",
        "adaptive_scan_seconds_balanced",
        "adaptive_scan_seconds_conservative",
        "max_plan_age_seconds_aggressive",
        "max_plan_age_seconds_balanced",
        "max_plan_age_seconds_conservative",
        "pending_entry_check_seconds",
        "active_trade_check_seconds",
        "premium_stagnation_candles",
        "minimum_sl_improvement_ticks",
        "early_exit_min_conditions",
        "low_aggression_quantity_pct",
        "atm_scan_strike_span",
        "major_strike_step",
        "contract_reselection_minutes",
        "max_hop_strikes",
        "sl_modify_throttle_seconds",
        "telegram_command_cooldown_seconds",
        "telegram_duplicate_window_seconds",
        "expiry_day_max_lots",
        "backtest_entry_validity_candles",
        "real_entry_poll_seconds",
        "real_entry_timeout_seconds",
        "real_protection_retry_count",
        "real_protection_retry_delay_seconds",
        "max_tick_age_seconds",
        "max_quote_age_seconds",
        "websocket_reconnect_max_attempts",
        "max_full_quote_batch_size",
        "real_broker_reconcile_poll_seconds",
        "event_driven_min_scan_interval_ms",
    ):
        settings[key] = _int(settings.get(key), int(DEFAULT_OPTIONS_AUTO_SETTINGS[key]))

    settings["mode"] = str(settings.get("mode") or MODE_PAPER).strip().upper()
    settings["underlying"] = str(settings.get("underlying") or "NIFTY").strip().upper()
    settings["strategy_profile"] = str(settings.get("strategy_profile") or "BALANCED").strip().upper()
    entry_mode = str(settings.get("entry_dependency_mode") or "PROFILE").strip().upper()
    if entry_mode in {"SIMPLE", "SIMPLE_OHLCV", "MAIN_APP_STYLE", "OHLCV_VOLUME", "OHLCV_VOLUME_PROFILE"}:
        entry_mode = "OHLCV_VOLUME_PROFILE"
    elif entry_mode in {"FULL", "FULL_CONFIRMATION", "CONFIRMATION_STACK"}:
        entry_mode = "FULL_CONFIRMATION"
    else:
        entry_mode = "PROFILE"
    settings["entry_dependency_mode"] = entry_mode
    settings["expiry_preference"] = str(settings.get("expiry_preference") or "AUTO").strip().upper()
    settings["backtest_entry_mode"] = str(settings.get("backtest_entry_mode") or "NEXT_CANDLE_OPEN_PLUS_SLIPPAGE").strip().upper()
    settings["same_day_expiry_cutoff_time"] = str(settings.get("same_day_expiry_cutoff_time") or "11:30").strip()
    return settings
