APP_NAME = "TradeBot Intraday Stocks Terminal"
BROKER_ZERODHA = "Zerodha"

MODE_PAPER = "PAPER"
MODE_REAL = "REAL"
MODE_BACKTEST = "BACKTEST"
MODE_REPLAY = "REPLAY"
SUPPORTED_MODES = {MODE_PAPER, MODE_REAL, MODE_BACKTEST, MODE_REPLAY}
SIMULATED_ORDER_MODES = {MODE_PAPER, MODE_BACKTEST, MODE_REPLAY}

MODE_STATE_NO_SESSION = "NO_SESSION"
MODE_STATE_PAPER_LOGGED_IN = "PAPER_LOGGED_IN"
MODE_STATE_REAL_LOGGED_IN = "REAL_LOGGED_IN"
MODE_STATE_BACKTEST_ACTIVE = "BACKTEST_ACTIVE"
MODE_STATE_PAPER_SESSION_RUNNING = "PAPER_SESSION_RUNNING"
MODE_STATE_REAL_SESSION_RUNNING = "REAL_SESSION_RUNNING"
MODE_STATE_SESSION_LOCKED = "SESSION_LOCKED"
MODE_STATE_ERROR_LOCKED = "ERROR_LOCKED"

EXCHANGE_NSE = "NSE"
EXCHANGE_BSE = "BSE"
SUPPORTED_EXCHANGES = {EXCHANGE_NSE, EXCHANGE_BSE}

SIDE_LONG = "LONG"
SIDE_SHORT = "SHORT"
SIDE_NO_TRADE = "NO TRADE"
SUPPORTED_SIDES = {SIDE_LONG, SIDE_SHORT}

ORDER_LIMIT_ONLY = "LIMIT_ONLY"
ORDER_MARKET_ALLOWED = "MARKET_ALLOWED"

ORDER_STATUS_PENDING = "PENDING"
ORDER_STATUS_COMPLETE = "COMPLETE"
ORDER_STATUS_REJECTED = "REJECTED"
ORDER_STATUS_CANCELLED = "CANCELLED"

MAX_STOCKS = 5
DEFAULT_CANDLE_INTERVAL = "1minute"
DEFAULT_MIN_ENTRY_SCORE = 70
DEFAULT_MIN_RISK_REWARD = 1.5
DEFAULT_PAPER_BALANCE = 100000.0

SESSION_STATUS_IDLE = "IDLE"
SESSION_STATUS_RUNNING = "RUNNING"
SESSION_STATUS_STOPPED = "STOPPED"
SESSION_STATUS_LOCKED = "LOCKED"
SESSION_STATUS_KILLED = "KILLED"
